pull_request_rules:
  - name: ci testing kalo sukses ke squash dengan label
    conditions:
      - base=main
      - label=ready-to-merge
    actions:
      label:
        add:
            - sudah direview !
      comment:
        message: terima kasih atas kontribusinya @{{author}} !
      merge:
        method: squash
  - name: sql label
    conditions:
      - files~=\.sql$
    actions:
      label:
        add:
          - sql files
          - request tim sql untuk review
  - name: markdown label
    conditions:
      - files~=\.md$
    actions:
      label:
        add:
          - markdown files
          - request sql team untuk review
  - name: review sql team untuk file markdown
    conditions:
      - label=markdown files
    actions:
      request_reviews:
        teams:
          - "@bellshade/sql-team"
